### ISSUE TITLE
TextEditor.scrollToBottom is deprecated.

### ISSUE THREAD

**Issue by BBrown4** [acemod/language-arma-atom#98] opened 2017-10-30 20:11 UTC
This is now a view method. Call TextEditorElement::scrollToTop instead.
```
TextEditor.scrollToBottom (<embedded>:5509:18)
<unknown> (C:\Users\bmxch\.atom\packages\language-arma-atom\lib\open-latest-rpt-file.coffee:32:17)
```

**Comment by jonpas** [comment] 2017-10-30 20:19
Duplicate of #92.

**Closed as completed by jonpas** 2017-10-30 20:19 UTC
Labels: duplicate
