### ISSUE TITLE
isEqualTo is a Operator but dont have a Color Coding

### ISSUE THREAD

**Issue by jokoho48** [acemod/language-arma-atom#65] opened 2016-04-18 20:07 UTC
isEqualTo dont have a Color Coding but other isEqualX

**Comment by jonpas** [comment] 2016-04-18 21:07
Tagging #31 

I am not sure, `isEqualTo` directly compares just like `==` (but with obvious other differences), white other `isEqualTypeX` compare to a type or types, and is therefore a command.

I'd say leave as is.

**Comment by jonpas** [comment] 2016-05-27 01:09
No input for over a month, closing as by design.

**Closed as completed by jonpas** 2016-05-27 01:09 UTC
Labels: bug, syntax-highlighting
