### ISSUE TITLE
Toggle-line-comments doesn't activate that functionality despite the keybind being valid

### ISSUE THREAD

**Issue by dslyecxi** [acemod/language-arma-atom#58] opened 2016-01-23 04:49 UTC
I've run into an issue where Ctrl-/ shows as activating the editor:toggle-line-comments functionality, but nothing actually happens in the file. Rebinding this (to e.g. ctrl-i) doesn't change the behavior.  This only occurs when the language-arma-atom module is active. 

An example of the keybind resolver when I use the ctrl-/ bind:
https://i.gyazo.com/a159d9f5fe9f3ec0e75ed587a1175268.png

**Comment by kymckay** [comment] 2016-01-23 11:13
Sorry to say I can't reproduce this one:

![](http://i.imgur.com/m9qlDAG.gif)

Seems like it might be limited to something more specific, but can't think of any candidates off the top of my head.

**Comment by jokoho48** [comment] 2016-01-23 14:13
@dslyecxi what kind of keyboard did you use

**Comment by jonpas** [comment] 2016-01-26 22:35
I can't reproduce either.

@dslyecxi what other packages are you using?

**Comment by jonpas** [comment] 2016-02-22 17:49
Seems like no one can reproduce it and no more info since a month ago, closing.

**Closed as completed by jonpas** 2016-02-22 17:49 UTC
Labels: bug, need more info, can't reproduce
