### ISSUE TITLE
Syntax highlighting missing for isEqualTo

### ISSUE THREAD

**Issue by dedmen** [acemod/language-arma-atom#91] opened 2017-05-23 10:04 UTC
isEqualTo is defined as a comparison operator 
https://github.com/acemod/language-arma-atom/blob/76d1b96906974e257b969607939792b0cbb274da/grammars/sqf.json#L44
Which makes it appear white. Which can cause oopsies like this
![](https://dedmen.de/sharex/EpvjV6Gh.png)

**Comment by kymckay** [comment] 2017-05-23 10:56
Duplicate of #65 

However, I'd actually be in favour of changing it

**Comment by dedmen** [comment] 2017-05-23 11:27
isEqualTo is a real binary command.. (Just like != and == but whatever)
What benefit does it actually have to define it as operator? Besides all operators having the same color?

**Comment by jonpas** [comment] 2017-05-23 13:41
Spelling it correctly in your screenshot would be nice, haha. 

I am fine with either, we'll set it as to whatever general consensus is. I might even prefer command highlight as it is made of chars rather than symbols.

**Comment by dedmen** [comment] 2017-05-23 15:48
The Screenshot just shows an error that I just shipped in a TFAR beta build.. Because I didn't see because no highlighting

**Comment by dedmen** [comment] 2017-08-21 06:19
The previous reports were closed because `isEqualTo` was considered a operator like `==` or `!=` or `>`.
There is no problem that `==` and stuff are not highlighted as you can't really typo these.

But with `isEqualTo` highlighting is important because as seen in my screenshot you can easilly typo that and if you do.. Then you won't see it because it has the same color when it's correct or wrong.

```sqf
test isEqualTo test;
test == test;
```
As you can see this also highlights isEqualTo and... `==` too apparently

**Comment by jonpas** [comment] 2017-08-21 15:06
That convinces me, will change it with next update.

**Closed as completed** 2017-08-21 20:39 UTC
Labels: bug, syntax-highlighting
