### ISSUE TITLE
#define autocompletition adds second #

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/language-arma-atom#43] opened 2015-12-06 22:51 UTC
Typing `#def` and then pressing tab to autocomplete results in `##define keyword value`.

**Comment by jonpas** [comment] 2015-12-07 05:31
That is because the match pattern is `define` without leading hashtag, Atom for some reason doesn't support it, they might have fixed it since then though or there could be another way.

**Comment by jonpas** [comment] 2015-12-08 13:58
@BaerMitUmlaut what would we wanted behaviour? You type `#de` (for example) and output is `#define` or you type `def` (for example) and output is `#define`? I see in C++ it seems to be that you type it without the leading hashtag and autocompletes adds it.

**Comment by simon84** [comment] 2015-12-19 01:18
Any progress in this discussion? For me its only a matter of taste and not a bug.

**Comment by thojkooi** [comment] 2015-12-19 09:36
I'd go with the C++ style for this. So nothing would change.

**Comment by jonpas** [comment] 2015-12-19 09:51
Same here, closing then.

**Closed as completed by jonpas** 2015-12-19 09:51 UTC
Labels: auto-completion, by design
